name: 'markdown-image-uploader'
author: 'rxrw'
description: 'Automatically Transfer Your Markdown Local Image to Your Like CDNs'
runs:
  using: 'docker'
  image: 'actions/Dockerfile'
  env:
    CLIENT_NAME: ${{ inputs.client_name }}
    ACCESS_KEY: ${{ inputs.access_key }}
    ACCESS_SECRET: ${{ inputs.access_secret }}
    ENDPOINT: ${{ inputs.endpoint }}
    BUCKET_NAME: ${{ inputs.buck_name }}
    VISIT_URL: ${{ inputs.visit_url }}
    CONTENT_PATH: ${{ inputs.content_path }}
branding:
  icon: 'circle'
  color: 'purple'
inputs:
  client_name:
    description: "aliyun or qiniu"
    required: false
    default: "qiniu"
  content_path:
    description: "Your Markdown's Folder Path"
    required: false
    default: 'content'
  access_key:
    description: 'Access Key Id'
    required: true
  access_secret:
    description: 'Access Key Secret'
    required: true
  endpoint:
    description: 'Endpoint or Region(For Qiniu)'
    required: true
  bucket_name:
    description: 'Bucket Name'
    required: true
  visit_url:
    description: 'Visit Url'
    required: true
