# .github/workflows/release.yaml

on:
  release:
    types: [created]

jobs:
  release:
    name: release linux/amd64
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, windows/386, windows/amd64, darwin/386, darwin/amd64
        goos: [linux, windows, darwin]
        goarch: ["386", amd64]

    steps:
    - uses: actions/checkout@v2

    - uses: wangyoucao577/go-release-action@v1.14
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goversion: 1.15
        binary_name: uploader
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
